spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://rest-mvc:8080
          predicates:
            - Path=/api/v1/*/**
        - id: reactive-mongo
          uri: http://reactive:8080
          predicates:
            - Path=/api/v2/*
        - id: 30-spring-6-reactive-mongocd..
          uri: http://reactive-mongo:8080
          predicates:
            - Path=/api/v3/*
        - id: spring-6-auth-server
          uri: http://auth-server:9000
          predicates:
           - Path=/oauth2/**
